name: ARIMA Model Workflow
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ensure `results/` Directory Exists
        run: mkdir -p results/
  
      - name: Set Write Permissions
        run: chmod -R 777 results/

      - name: Make `run.sh` Executable
        run: chmod +x run.sh

      - name: Run executable bash script
        run: bash ./run.sh

      - name: Debug Results Directory (Continue on Failure)
        run: ls -lah results/
        continue-on-error: true

      - name: Upload Reports & Plots
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/**        

